### ISSUE TITLE
[sdk] multi-chain multi-storage protocol support for beacons

### ISSUE THREAD

**Issue by microchipgnu** [zestymarket/sdk#99]
I would like to use the beacons for https://3xr.space to collect data, but I don't want to use Zesty NFTs. Mostly because I use NEAR NFTs and 3XR is strongly tied to the NEAR Protocol. Discussed this with @limbofeather 

3XR custom spaces are NEAR NFTs (feature launching soon). 

Ideal scenario for a request is the following:

Client https://3xr.space/custom/{id}

`POST /api/v1/space/${spaceId}`

**Request Body**
**item** `object`

**item.id** `string` 
**item.metadataReference** `string`
**item.chain** `string` (optional)
**item.network** `string` (optional) 

**Example**
```ts
{
  id: "QmpZLvnAVsxI9IOIRbzTaH3iOK6X4tb69xLZzmL8jno:hellovirtualworld.mintbase1.near",
  metadataReference: "https://arweave.net/QmpZLvnAVsxI9IOIRbzTaH3iOK6X4tb69xLZzmL8jno",
  chain: "near",
  network: "mainnet",
}
```

**Comment by limbofeather** [comment]
I'm 100% in favour of making Zesty's beacon functionality network/chain agnostic, thanks @microchipgnu for opening this issue. An alternative to providing the information inside the request body, is to include the chain/network + token ID info in the request URL.

So in order to increment the visit on this particular token, it would look something like a `PUT` to this:

`https://beacon.zesty.market/api/v1/${chain}/${network}/space/${spaceId}`

The data would be retrieved with a `GET` to the same URL.

What do you think?

**Comment by microchipgnu** [comment]
Sorry for taking so long to coming back to this. I 100% agree with your suggestion.

Let me know when I can start hitting these.

**Comment by limbofeather** [comment]
I think we can close for now since plans for integrating with NEAR are not high priority atm.
